[tool.poetry]
name = "sf-demo"
version = "0.1.0"
description = "Experiment to programmatically manage Salesforce data."
authors = ["Felix Fennell <felnne@bas.ac.uk>"]
readme = "README.md"
packages = [{include = "sf_demo", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
simple-salesforce = "^1.12.6"
environs = "^11.2.1"
streamlit = "^1.41.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.8.4"

[tool.ruff]
src = ["src"]
line-length = 120
target-version = "py12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
